S = struct;

names = {'Bingo','ErroAlt','ErroAlt1','FDrag','Fx','Fz','Gama','GCom', ...
    'GComp','GLat','Guiamento','Limite_Manobra','MachN','Massa', ...
    'MissDist','Stop_FugaAlvo','Stop_VMin','Stop_Queda','TetaCom', ...
    'ThetaAD','thetaadideal','Thrust','Vm','wldv','wldvM','Xm', ...
    'XTgt','Zm','ZTgt'};

fields = {'Bingo','ErroAlt','ErroAlt1','FDrag','Fx','Fz','Gama','GCom', ...
    'Gcomp','GLat','Guiamento','Limite_Manobra','MachN','Massa', ...
    'MissDist','Stop_FugaAlvo','Stop_VMin','Stop_Queda','TetaCom', ...
    'ThetaAD','thetaadideal','Thrust','Vm','wldv','wldvM','Xm', ...
    'XTgt','Zm','ZTgt'};

for k = 1:numel(names)
    if exist(names{k}, 'var')
        S.(fields{k}) = eval(names{k});
    else
        S.(fields{k}) = [];
    end
end
